#!/usr/bin/env bash

set -e

TEST_DIR="$1"
shift

TEST_FILE="$1"
shift

REMAINING_ARGS="$@"

cd "$TEST_DIR"
# We allow system site packages to make installing numpy/scipy less burdensome
virtualenv venv --system-site-packages
source venv/bin/activate
pip install -r requirements.txt
exec python "$TEST_FILE" $REMAINING_ARGS
