HYPERPARAMETERS = [
  dict(
    regularization_type='sgd.l1RegularizationAmount',
    regularization_amount=0.00000001
  ),
  dict(
    regularization_type='sgd.l1RegularizationAmount',
    regularization_amount=0.0000001
  ),
  dict(
    regularization_type='sgd.l1RegularizationAmount',
    regularization_amount=0.000001
  ),
  dict(
    regularization_type='sgd.l1RegularizationAmount',
    regularization_amount=0.00001
  ),
  dict(
    regularization_type='sgd.l1RegularizationAmount',
    regularization_amount=0.0001
  ),
  dict(
    regularization_type='sgd.l2RegularizationAmount',
    regularization_amount=0.000001
  ),
  dict(
    regularization_type='sgd.l2RegularizationAmount',
    regularization_amount=0.00001
  ),
  dict(
    regularization_type='sgd.l2RegularizationAmount',
    regularization_amount=0.0001
  ),
  dict(
    regularization_type='sgd.l2RegularizationAmount',
    regularization_amount=0.001
  ),
  dict(
    regularization_type='sgd.l2RegularizationAmount',
    regularization_amount=0.01
  ),
]
